# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20160819_1558'),
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
        ),
    ]
