# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_auto_20160819_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.Menu'),
        ),
    ]
