# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='parent',
        ),
    ]
