# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menus_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.Menus'),
        ),
    ]
