# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menus_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'ordering': ['title'], 'verbose_name': 'Menus', 'verbose_name_plural': 'Menus'},
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='menus',
            name='decs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
