# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20160817_0413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
