# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20160817_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='decs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b'),
        ),
    ]
