# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-18 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0006_auto_20160817_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='create_time',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='modified_time',
            new_name='modifiedtime',
        ),
        migrations.AddField(
            model_name='menu',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='mender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='decs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
