# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 07:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0008_treemenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='creater',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='mender',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.AddField(
            model_name='treemenu',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treemenu',
            name='createtime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 19, 7, 58, 28, 925423, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treemenu',
            name='decs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treemenu',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treemenu',
            name='mender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treemenu',
            name='modifiedtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 19, 7, 58, 39, 493162, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
